." Hi! This manual (man page) was written by dd86k.
." Please read man-pages(7) and groff_man(7) about the manual page format.
." 
."
.TH ddhx 1 "July 2017" POSIX "User manual"
.SH NAME
ddhx - Interactive hexadecimal file viewer.

.SH SYNOPSIS
.RI "ddhx " "file"

.R ddhx {--help|-h|--version}

.SH DESCRIPTION
.B ddhx
is a fast interactive hexadecimal file viewer with several search features that runs within the terminal.
.SH OPTIONS
.I
.IP file
File to open.

.SH SHORTCUTS

.IP q
Quits (closes) the program

.IP ENTER
Enters prompt

.IP a
Auto-adjust screen width (bytes per row).

.IP i
Displays file information.

.IP r|F5
Repaint display entirely.

.SH PROMPT AND COMMANDS
Pressing
.B ESC
or
.BR "ENTER" " (" "RETURN" ")"
will enter prompt mode, where commands and queries can be entered.

The one character commands are command aliases.

.B g|goto <Number>
.RS
Goto to position <Number> (bytes) in file. Supports hexadecimal.
.RE

.B i|info
.RS
Display file information.
.RE

.B o|offset <Offset>
.RS
Change offset type. Possible values are o (octal), d (decimal), or h (hexadecimal).
.RE

.B s|search <Type> <Value>
.RS
Search for data. Valid data can be:
.IP
.BR "byte" ", " "short" ", " "int" ", " "long" ", " "string" ", and " "wstring"
.RE

.B ss <Value>
.RS
Search UTF-8 string alias.
.RE

.B sb <Value>
.RS
Search byte alias.
.RE

.B r|refresh <Offset>
.RS
Refresh all panels and displays.
.RE

.SH NAVIGATION
Currently, the modifier key states on Posix platforms are unavailable. You are invited to use the
.B goto end
command.

.B Up/Down Arrows
.RS
Go backward or forward a line (by width).
.RE

.B Left/Right Arrow
.RS
Go backward or forward a byte
.RE

.B Home/End
.RS
Align to the line
.RE

.B CTRL+Home/CTRL+End
.RS
Go to begining or end of file
.RE

.SH FILE ATTRIBUTES
The information command will display different file attributes on different platforms:

.SS Under Windows

On Windows, the following file attributes (NTFS) will be displayed:
.IP r
Read-only. (FILE_ATTRIBUTE_READONLY)
.IP h
Hidden. (FILE_ATTRIBUTE_HIDDEN)
.IP s
System. (FILE_ATTRIBUTE_SYSTEM)
.IP a
Archive. (FILE_ATTRIBUTE_ARCHIVE)
.IP t
Temporary. (FILE_ATTRIBUTE_TEMPORARY)
.IP S
Sparse file. (FILE_ATTRIBUTE_SPARSE_FILE)
.IP c
Compressed. (FILE_ATTRIBUTE_COMPRESSED)
.IP e
Encrypted. (FILE_ATTRIBUTE_ENCRYPTED)
.RE

.SS Under Posix-compilant systems

.RB "The symbolic file permissions are displayed (although not exactly like the output of " "ls -l" ")."
The last character is the sticky bit indicator
.RB "(" "t" ")."

.SH WARNINGS
ddhx is still currently going under active development. Expect lots of bugs and crashes!
.SH NOTES
ddhx will clear the output on exit.
.SH BUGS
Currently, string searching may be inacurate with small chunks.
.SH CONTACT
Homepage:
.UR "https://github.com/dd86k/ddhx"
.UE